### ISSUE TITLE
при подключении к боту программа зависла, не выдает ошибку, невозможно отменить попытку соединения

### ISSUE THREAD

**Issue by MariyaKlimenko** [M-Sh-97/ChatApp#1]
шаги:
ввод ника , эпплай
ввод айпи бота, конект
что вижу:
программа очевидно пытается соединиться, ничего не происходит
что хочу видеть: 
если не выводит сообщение об ошибке, так как у вас программа еще без таймеров, можно было бы сделать возможным самому прервать попытку соединения

**Comment by M61Shaforostov** [comment]
Прежде всего, где-то с 12.12 по 14.12 были проблемы с роботом **на сайте преподавателя** (не принимал "звонки").
Уже сообщил, уже было исправлено.

**Comment by M61Shaforostov** [comment]
Сообщение об ошибке подключения уже обработано.
Хорошее предложение насчёт возможности прерывания; скорее всего, появится уже во время некомандной разработки. Однако сейчас попытка соединения длится 30 секунд (по умолчанию), и это не так и долго...
