### ISSUE TITLE
Непонятная работа программы при подключении

### ISSUE THREAD

**Issue by koha26** [M-Sh-97/ChatApp#17]
Шаги по воспроизведению проблемы:
1. Запустить программу
2. Ввести свой ник и нажать "Войти"
3. Ввести "files.litvinov.in.ua" или "8.8.8.8" и нажать "Подключиться" 

Ожидаемый результат:
Уведомит или о начале диалога или о невозможности подключения. 

Фактический результат:
Программа ничего не выполняет. Даже по истечению введенных 30 секунд разработчиком ничего не выполняет. Чтобы закрыть программу приходиться пользоваться "Диспетчером задач".

**Comment by M61Shaforostov** [comment]
Всё-таки дождался начала диалога, да :smile:? Пока есть активное соединение, попытки закрытия программы блокируются.
