### ISSUE TITLE
Общение с ботом (показ пустых принятых сообщений)

### ISSUE THREAD

**Issue by koha26** [M-Sh-97/ChatApp#18]
Шаги по воспроизведению проблемы:
1. Запустить программу
2. Ввести ник и нажать "Войти"
3. Ввести "files.litvinov.in.ua" и нажать "Подключиться"
4. Написать сообщение и нажать "Отправить"

Ожидаемый результат:
Бот ответит нам, дублируя наше сообщения. Программа примет это сообщение и покажет его в окне диалога. 

Фактический результат:
Показывает пустое сообщение принятое от бота. 
![bugmsh97](https://cloud.githubusercontent.com/assets/15383640/12378180/dae835ec-bd3e-11e5-9c99-71dc866b6fec.PNG)

**Comment by M61Shaforostov** [comment]
На самом деле обратно первый абзац сообщения приходит в целости и сохранности; режим отладки показал это.
Как я понял, робот оправляет отдельно команду и текст сообщения (дважды используется `Writer.flush()`). В этой версии (3.0 или 3.1) `Connection.receive()` между приёмом первого и второго "попадает" в момент, когда в потоке не появились новые данные, и метод `input.ready()` возвращает ложь (нет разделителей строк - буфер не "готов" к считыванию).
В результате создаётся объект `MessageCommand`, в котором `text == ""`, а сам текст сообщения игнорируется как команда, не соответствующая ни одному протокольному образцу.
Забавно то, что, когда задерживалось выполнение программы в `Connection.receive()`, данные обрабатывались правильно.

**Comment by M61Shaforostov** [comment]
Сейчас вызов `Connection.receive()` фактически не является блокирующим, из-за чего подгружается процессор. Буду переделывать его в "обратную сторону", но с одноабзацными версиями программы (в том числе с роботом), скорее всего, новая работать не станет.

**Comment by dimalit** [comment]
Миша, хорошо, что есть тестеры - бдят! ;)

**Comment by M61Shaforostov** [comment]
Новая выпуск (4.0) всё же поддерживает одноабзацные версии.
В случае с роботом проблема - в нём самом: он по отдельности отправляет "MESSAGE" и непосредственный текст.
Если переделывать под него `Connection.receive()`, то придётся внутри метода копаться в созданном объекте `Command` и писать условие дополнительного приёма информации из разъёма до возврата управления; это сделает `Connection` **более зависимым** от `Command`, что противоречит принципу ООП.
Что интересно: хотя мой чат посылает и командную фразу, и последующий текст одним "куском", робот правильно распознаёт инфу (при отладке выявил). Таким образом, логичнее подправить именно робота (просьба к @dimalit).
