### ISSUE TITLE
Невозможно подключиться к себе.

### ISSUE THREAD

**Issue by archy322** [M-Sh-97/ChatApp#2]
Шаги по воспроизведению проблемы: 
1. Запустить программу.
2. Заполнить поле логина.
3. В поле ip ввести "127.0.0.1".
4. Нажать Connect.
Ожидаемый результат:
Подключаемся к себе.
Фактический результат:
Программа не подключается, невозможно сделать ничего кроме выхода из программы.

**Comment by M61Shaforostov** [comment]
Не, ну доводи до конца: при такой попытке появляется окно с сообщением о "занятости" и запросом на повтор "звонка" и после отказа доступно либо закрывать прогу, либо нажимать безрезультатно "Connect".

**Comment by M61Shaforostov** [comment]
Впрочем, дефект - налицо: "занято" приводит прогу будто в ступор.
Устранено. Имею в виду, что возможно будет нормально "звонить" после занято.

**Comment by M61Shaforostov** [comment]
А в подключении к себе самому, по-моему, есть смысл. Это чуть сложнее сделать, ибо нужно использовать то ли другой локальный адрес, то ли другой порт.
А за пример представления сообщений взять "ВК" (отправленное не дублируется как полученное)...

**Comment by M61Shaforostov** [comment]
Для подключения к себе было достаточно подправить условие отправки "занято" в приветствии :).
