### ISSUE TITLE
Зависает при неудачном подключении 

### ISSUE THREAD

**Issue by mgarna** [M-Sh-97/ChatApp#3]
Запустить ChatApp.
Ввести ник. 
Ввести ip
Connect
Ожидаемый результат:
Сообщение о невозможности подключения или подключение
Фактический результат:
Программа зависла

**Comment by M61Shaforostov** [comment]
Она не зависает, а ожидает 30 секунд (по умолчанию), после чего становится возможным сделать другой / повторить "звонок".
Предложение по сообщению о неудаче уже было.
