### ISSUE TITLE
Пробел в нике

### ISSUE THREAD

**Issue by mgarna** [M-Sh-97/ChatApp#4]
Шаги по воспроизведению проблемы:
1. Запустить ChatApp.
2. В поле Nickname ввести ник с использованием пробела(пример: Name Surname). Нажать Apply
3. Ввести ip и нажать Connect.

Ожидаемый результат:
Сообщение с просьбой не использовать знак "пробел" при введении ника, либо возможность пробела в нике.

Фактический результат:
Программа зависает

**Comment by M61Shaforostov** [comment]
В программе не было запрета на пробелы в псевдониме пользователя! Уж, тем более, не зависает она ни при его применении, ни при попытке соединения под ним.
