### ISSUE TITLE
Не сохраняет контакт

### ISSUE THREAD

**Issue by mgarna** [M-Sh-97/ChatApp#5]
Шаги по воспроизведению проблемы:
1. Запустить ChatApp.
2. Позвонить одному человеку - чтобы его IP добавился в список контактов.
3. Перезапустить программу.

Ожидаемый результат:
В списке контактов сохранился добавленный в него в п.2. человек.

Фактический результат:
Не сохраняет

**Comment by M61Shaforostov** [comment]
Да, наверное, со считкой из файла проблемы.
Ещё предполагаю, что может затереться при загрузке пользователей с сервера.
