### ISSUE TITLE
Отправка пустых сообщений

### ISSUE THREAD

**Issue by DmitriiZinevich** [M-Sh-97/ChatApp#6]
Шаги:
1)Запустить "чат"
2)Ввести ник и позвонить
3)Отправить пустое сообщение

Ожидаемый результат: программа не должна отослать пустое сообщение
Фактический результат: программа его отправляет

P.S. Это не страшно, однако это может привести к "засорению" чата

**Comment by M61Shaforostov** [comment]
Чего таить: это не соответствует здравому смыслу.
Учтено.
