### ISSUE TITLE
Проблема при подключии к боту

### ISSUE THREAD

**Issue by DimaKovalchuk** [M-Sh-97/ChatApp#7]
Шаги по воспроизведению проблемы:
1. Запустил программу.
2.Ввел Local nick
3. Нажал Apply
4. Ввел Remoute IP-adress (files.litvinov.in.ua)
5. Нажал Connect

Ожидаемый результат:
 Подключение к боту

Фактический результат:
Программа зависла.

**Comment by M61Shaforostov** [comment]
Об этом уже упоминалось в проблеме № 1.
Опять же, в роботе - проблема.
