### ISSUE TITLE
Не возможно ввести Remoutenicname.

### ISSUE THREAD

**Issue by DimaKovalchuk** [M-Sh-97/ChatApp#8]
Шаги по воспроизведению проблемы:
1. Запустил программу.
2.Ввел Local nick
3. Нажал Apply
4. Ввел Remoute IP-adress (files.litvinov.in.ua)
5. Нажал Connect
6. Хотел ввести Remoutenicname

Ожидаемый результат:
Получилось ввести Remoutenicname

Фактический результат:
Ввести Remoutenicname не возможно.

**Comment by M61Shaforostov** [comment]
Не вижу смысла делать доступным для редактирования это поле. Решать за собеседника, как его зовут? Поле "Удалённый пользователь" только показывает полученное с адреса прозвище, под которым "получатель звонка" вошёл в чат.
