### ISSUE TITLE
Нет возможности изменить ник без перезагрузки приложения.

### ISSUE THREAD

**Issue by ikurc** [M-Sh-97/ChatApp#9]
Шаги по воспроизведению проблемы:
1. Запустить один экземпляр ChatApp.
2. Ввести имя пользователя - нажать Apply

Фактический результат:
Программа блокирует текстовое поле с именем и кнопку Apply, тем самым не давая возможности изменить имя пользователя в случае неправильного(ошибочного) ввода. Чтобы изменить ник программу приходится перезагружать.

Ожидаемый результат:
Возможность изменить ник после нажатия кнопки Apply.
![1123213](https://cloud.githubusercontent.com/assets/15365823/11917726/fe66e4f2-a71b-11e5-93f0-35470e6b1b64.JPG)

**Comment by M61Shaforostov** [comment]
Вообще как попало менять входные данные не "канонично". Тем более, во время активного соединения.

**Comment by M61Shaforostov** [comment]
Можно переоформить применение прозвища на вход в систему и выход из неё (logging in & out), что вполне уместно.
Надеюсь, что такое решение подойдёт к ожиданиям.

**Comment by valeriya19** [comment]
Подожди-ка,а было хоть слово о том,что ник нужно менять?давай не искать того,о чем и речи не было.

**Comment by M61Shaforostov** [comment]
Ошибка при вводе - вполне обоснованный повод для некоего улучшения.
Если компом (в том числе и нашей программкой) пользуются несколько человек, то логично дать им возможность входа под другим, своим именем без перезапуска.

**Comment by M61Shaforostov** [comment]
В выпуске 2.0 своей одиночной чат-проги я уже сделал такое улучшение; можешь оценить непредусмотренную "находку" :point_left:.

**Comment by valeriya19** [comment]
ну ты же Бог

**Comment by M61Shaforostov** [comment]
Да ладно :smile:...
